iproute2.postinst: use setcap -r instead of empty set
Calling setcap with an empty strings does not remove the xattr, but sets
it to an empty set, which breaks programs with ambient caps forking and
exec'ing ip.
Use setcap -r instead to remove the xattr if the user chooses to do so.

Thanks to Mantas Mikulėnas for spotting the error!

diff --git a/debian/iproute2.postinst b/debian/iproute2.postinst
--- a/debian/iproute2.postinst
+++ b/debian/iproute2.postinst
@@ -14,13 +14,16 @@ case "$1" in
 
             # Allow dpkg-reconfigure to remove caps
             if test "$RET" = "true"; then
-                CAPS="cap_dac_override,cap_sys_admin,cap_net_admin=ep"
+                if ! setcap "cap_dac_override,cap_sys_admin,cap_net_admin=ep" /bin/ip; then
+                   echo "Setcap failed on /bin/ip, ip vrf exec will not be runnable by non-root" >&2
+                fi
             else
-                CAPS=""
-            fi
-
-            if ! setcap "$CAPS" /bin/ip; then
-                echo "Setcap failed on /bin/ip, ip vrf exec will not be runnable by non-root" >&2
+                # setcap -r fails if the xattr is not present
+                if getcap /bin/ip | grep -qs "/bin/ip"; then
+                    if ! setcap "-r" /bin/ip; then
+                       echo "Setcap -r failed on /bin/ip, could not remove capabilities" >&2
+                    fi
+                fi
             fi
         fi
     ;;
